// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmployeeHandler is an autogenerated mock type for the EmployeeHandler type
type EmployeeHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *EmployeeHandler) Add() {
	_m.Called()
}

// List provides a mock function with given fields:
func (_m *EmployeeHandler) List() {
	_m.Called()
}

type mockConstructorTestingTNewEmployeeHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmployeeHandler creates a new instance of EmployeeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmployeeHandler(t mockConstructorTestingTNewEmployeeHandler) *EmployeeHandler {
	mock := &EmployeeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
