// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PayrollHandler is an autogenerated mock type for the PayrollHandler type
type PayrollHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *PayrollHandler) Add() {
	_m.Called()
}

// Detail provides a mock function with given fields:
func (_m *PayrollHandler) Detail() {
	_m.Called()
}

// List provides a mock function with given fields:
func (_m *PayrollHandler) List() {
	_m.Called()
}

type mockConstructorTestingTNewPayrollHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewPayrollHandler creates a new instance of PayrollHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPayrollHandler(t mockConstructorTestingTNewPayrollHandler) *PayrollHandler {
	mock := &PayrollHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
