// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SalaryHandler is an autogenerated mock type for the SalaryHandler type
type SalaryHandler struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *SalaryHandler) List() {
	_m.Called()
}

type mockConstructorTestingTNewSalaryHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewSalaryHandler creates a new instance of SalaryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSalaryHandler(t mockConstructorTestingTNewSalaryHandler) *SalaryHandler {
	mock := &SalaryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
